package com.jamakharch.category

object Classifier {

    private data class Rule(val keyword: String, val category: Category)

    private val rules = listOf(
        Rule("bigbasket", Category.GROCERY),
        Rule("zepto", Category.GROCERY),
        Rule("blinkit", Category.GROCERY),
        Rule("dmart", Category.GROCERY),
        Rule("grocery", Category.GROCERY),
        Rule("supermarket", Category.GROCERY),
        Rule("fresh", Category.GROCERY),
        Rule("chicken", Category.GROCERY),
        Rule("meat", Category.GROCERY),
        Rule("mutton", Category.GROCERY),
        Rule("fish", Category.GROCERY),
        Rule("vegetable", Category.GROCERY),
        Rule("milk", Category.GROCERY),

        Rule("1mg", Category.MEDICINE),
        Rule("netmeds", Category.MEDICINE),
        Rule("pharmeasy", Category.MEDICINE),
        Rule("apollo", Category.MEDICINE),
        Rule("medicine", Category.MEDICINE),
        Rule("medical", Category.MEDICINE),
        Rule("medico", Category.MEDICINE),
        Rule("pharmacy", Category.MEDICINE),

        Rule("iocl", Category.FUEL),
        Rule("bpcl", Category.FUEL),
        Rule("hpcl", Category.FUEL),
        Rule("petrol", Category.FUEL),
        Rule("fuel", Category.FUEL),
        Rule("indian oil", Category.FUEL),

        Rule("oyo", Category.TRAVEL),
        Rule("makemytrip", Category.TRAVEL),
        Rule("make my trip", Category.TRAVEL),
        Rule("goibibo", Category.TRAVEL),
        Rule("booking.com", Category.TRAVEL),
        Rule("airbnb", Category.TRAVEL),
        Rule("agoda", Category.TRAVEL),
        Rule("yatra", Category.TRAVEL),
        Rule("cleartrip", Category.TRAVEL),
        Rule("easemytrip", Category.TRAVEL),
        Rule("marriott", Category.TRAVEL),
        Rule("hyatt", Category.TRAVEL),
        Rule("radisson", Category.TRAVEL),
        Rule("hilton", Category.TRAVEL),
        Rule("ibis", Category.TRAVEL),
        Rule("taj hotel", Category.TRAVEL),
        Rule("resort", Category.TRAVEL),
        Rule("homestay", Category.TRAVEL),
        Rule("hostel", Category.TRAVEL),
        Rule("lodge", Category.TRAVEL),
        Rule("indigo", Category.TRAVEL),
        Rule("vistara", Category.TRAVEL),
        Rule("spicejet", Category.TRAVEL),
        Rule("air india", Category.TRAVEL),
        Rule("airline", Category.TRAVEL),
        Rule("flight", Category.TRAVEL),
        Rule("airways", Category.TRAVEL),

        Rule("swiggy", Category.FOOD),
        Rule("zomato", Category.FOOD),
        Rule("dominos", Category.FOOD),
        Rule("pizza", Category.FOOD),
        Rule("restaurant", Category.FOOD),
        Rule("cafe", Category.FOOD),
        Rule("hotel", Category.FOOD),
        Rule("caterer", Category.FOOD),
        Rule("dining", Category.FOOD),
        Rule("canteen", Category.FOOD),

        Rule("uber", Category.TRANSPORT),
        Rule("ola", Category.TRANSPORT),
        Rule("metro", Category.TRANSPORT),
        Rule("bus", Category.TRANSPORT),
        Rule("taxi", Category.TRANSPORT),
        Rule("rail", Category.TRANSPORT),
        Rule("irctc", Category.TRANSPORT),
        Rule("auto", Category.TRANSPORT),
        Rule("cab", Category.TRANSPORT),

        Rule("amazon", Category.SHOPPING),
        Rule("amazo", Category.SHOPPING),
        Rule("flipkart", Category.SHOPPING),
        Rule("myntra", Category.SHOPPING),
        Rule("ajio", Category.SHOPPING),
        Rule("meesho", Category.SHOPPING),
        Rule("tata cliq", Category.SHOPPING),
        Rule("shoes", Category.SHOPPING),
        Rule("clothing", Category.SHOPPING),
        Rule("fashion", Category.SHOPPING),

        Rule("netflix", Category.ENTERTAINMENT),
        Rule("prime video", Category.ENTERTAINMENT),
        Rule("hotstar", Category.ENTERTAINMENT),
        Rule("bookmyshow", Category.ENTERTAINMENT),
        Rule("pvr", Category.ENTERTAINMENT),
        Rule("spotify", Category.ENTERTAINMENT),
        Rule("youtube", Category.ENTERTAINMENT),
        Rule("cinema", Category.ENTERTAINMENT),
        Rule("movie", Category.ENTERTAINMENT),

        Rule("electricity", Category.UTILITIES),
        Rule("water", Category.UTILITIES),
        Rule("gas", Category.UTILITIES),
        Rule("broadband", Category.UTILITIES),
        Rule("recharge", Category.UTILITIES),
        Rule("bill pay", Category.UTILITIES),
        Rule("mobile", Category.UTILITIES),

        Rule("insurance", Category.HEALTH),
        Rule("premium", Category.HEALTH),
        Rule("health", Category.HEALTH),
        Rule("policy", Category.HEALTH),

        Rule("mutual fund", Category.INVESTMENT),
        Rule("ppf", Category.INVESTMENT),
        Rule("sip", Category.INVESTMENT),
        Rule("nps", Category.INVESTMENT),
        Rule("mutual", Category.INVESTMENT),
        Rule("investment", Category.INVESTMENT),
        Rule("nifty", Category.INVESTMENT),
        Rule("sensex", Category.INVESTMENT),
        Rule("stocks", Category.INVESTMENT),
        Rule("bonds", Category.INVESTMENT),
        Rule("etf", Category.INVESTMENT),
        Rule("dividend", Category.INVESTMENT),

        Rule("school", Category.SCHOOL),
        Rule("college", Category.SCHOOL),
        Rule("university", Category.SCHOOL),
        Rule("tuition", Category.SCHOOL),
        Rule("fees", Category.SCHOOL),
        Rule("academy", Category.SCHOOL),
        Rule("coaching", Category.SCHOOL),
        Rule("institute", Category.SCHOOL),
        Rule("vidyalaya", Category.SCHOOL),
        Rule("vidya", Category.SCHOOL),
        Rule("byjus", Category.SCHOOL),
        Rule("unacademy", Category.SCHOOL),
        Rule("vedantu", Category.SCHOOL),
    )

    fun classify(merchant: String, overrideLookup: ((String) -> Category?)? = null): Category {
        overrideLookup?.invoke(merchant.lowercase())?.let { return it }
        val lower = merchant.lowercase()
        return rules.firstOrNull { lower.contains(it.keyword) }?.category ?: Category.OTHERS
    }
}
